# В этом файле уже 3 сервиса
version: '3'
services:
  # Постгрес база в отдельном контейнере
  postgres:
    # Устанавливаем готовый образ
    image: postgres 
    # Задаем глобальные переменные для доступа к PG
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow
    restart: always

  # Airflow в отдельном контейнере
  airflow:
    # Сборка из Dockerfile
    build: .
    restart: always
    # Определчет порядок запуска сервисов
    depends_on:
      - postgres
#    args:
      # ошибка ImportError: cannot import name 'soft_unicode' from 'markupsafe'
#      PYTHON_DEPS: MarkupSafe==2.0.1 
    # Airflow поддерживает конфигурирование переменных из конфиг файла
    # https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html
    environment:
      - AIRFLOW__CORE__FERNET_KEY=HXJmviZ45J6R0bM1DFFij0JJ1ca_JMDWo9Z-Q-wqsFk= # Для шифрования подключений
      - AIRFLOW__WEBSERVER__SECRET_KEY=b27dfe9846d048294adc0df96ad43239fa325db739a0a69a60672e3e6272
    # Пробрасываем порты
    ports:
      - 8001:8080
    # Пробрасываем папку с дагами
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8002:8080
